### ISSUE TITLE
Collapse categories list on mobile

### ISSUE THREAD

**Issue by BalestraPatrick** [BalestraPatrick/HomeKitty#1]
Right now, the categories list is always displayed even on mobile. Since there are quite a few categories, it takes a lot of space away from the real content. 
We should create a button that shows the categories only upon user interaction (behaving pretty much like the hamburger button at the top right).
![img_2ba29115c26f-1](https://user-images.githubusercontent.com/3658887/30951854-68debf50-a425-11e7-8606-6115aca8bca8.jpeg)

**Comment by BNTR** [comment]
I will try to handle that =)
