### ISSUE TITLE
Add reCAPTCHA to make sure a human is sending an email

### ISSUE THREAD

**Issue by BalestraPatrick** [BalestraPatrick/HomeKitty#112]
Lately, many bots have been spamming our email forms, so I think the issue may be solved by implementing a reCAPTCHA code.

**Comment by kimdv** [comment]
What is your idea? 
TO use the Google  reCAPTCHA V3? 

https://developers.google.com/recaptcha/docs/v3

**Comment by BalestraPatrick** [comment]
Yes, that’s the idea. I already have registered the property in my Google account but you can create your own if you want to implement it.
