### ISSUE TITLE
Create page for each accessory

### ISSUE THREAD

**Issue by BalestraPatrick** [BalestraPatrick/HomeKitty#18]
We could have a page for each accessory where we display more links to the accessory along with more information about each region of availability and so on.

**Comment by BNTR** [comment]
Hey @BalestraPatrick ! I think it's important to know how and what should page for accessory display, at least to proceed with tasks related to this (I'm about #5 ) =) Can you provider some info in this?

**Comment by BalestraPatrick** [comment]
Hey @BNTR! Yes, you are right. Let me provide you with more information and a small mockup of what this task consists of: 
The idea is to have a new page that is similar to the current `explore` page but instead of rendering a list of accessories, we only render one page. Instead of adding all the content to this new page, we can add a new file and then use the Leaf `import` syntax.
As you can see, we have the same data as in the usual accessory box. By having a full page for each accessory, we can also add more information about the region and also a voting system if we'd like.

Don't worry too much about the design but this is how the content should be structured! 😄 
![accessory-details](https://user-images.githubusercontent.com/3658887/31405883-9f65b0d6-adff-11e7-9d47-4aa68f0dc4a0.png)
