### ISSUE TITLE
Scripts/seed.sh Username and Database

### ISSUE THREAD

**Issue by fnoah** [BalestraPatrick/HomeKitty#19]
I don't know if this is a bug, but in the Scripts/seed.sh file you apparently used your username in order to connect to the PostgreSQL DB which will lead to problems on other machines.

`psql -U patrickbalestra -d patrickbalestra -p 5433 -a -f seed_categories.sql || (echo "🚨  Failed seed categories"; exit 1;)`

**Comment by BalestraPatrick** [comment]
Hey! 
Yes you should insert your database credentials in that script. We could specify your own credentials in the README. If you want, you can submit a PR and I will gladly merge it 👍
