### ISSUE TITLE
Create "Latest Accessories" section/page

### ISSUE THREAD

**Issue by BalestraPatrick** [BalestraPatrick/HomeKitty#2]
Right now, the homepage is a page that loads all the accessories without any specific category filter. 
The idea would be to have the homepage be the place where a featured accessory is shown at the top, and underneath it, the latest accessories added are sorted by date.

**Comment by fnoah** [comment]
I would like to try implementing this. 
Would this change only affect the `/` (root) homepage or also the `/explore` page, which seems to be identical to the homepage at the moment and how do you think the featured accessory should determined? Should it, at least for the beginning, just be the hardcoded database id of the item or do you want something like an algorithm to determine which accessory should be featured?

**Comment by BalestraPatrick** [comment]
Hey @fnoah, thanks a lot for stepping up!
Attached you can find an image of my idea of the new homepage. As you said, right now the `/` and `/explore` page render the same explore page (which loads all the accessories by default). Since the number of accessories is quickly growing, we probably don't want to display 100+ accessories.
The new homepage could simply display an image at the top that we can customize. The idea would be to have a sponsor that would like to feature a new accessory every week/month (or if none available, we can manually select one). For this reason, some design flexibility would be needed and I think an image would provide this kind of flexibility.
The next part would display the last 20 accessories sorted by date. We could also display a small string in the format `added 1d ago` in each accessory container. What do you think? 😄 
![group](https://user-images.githubusercontent.com/3658887/31096378-1e72ae96-a7bc-11e7-85a3-1ace22543efb.jpg)

**Comment by fnoah** [comment]
This sound great 👍
I think your suggested changed/improvements would totally make sense. Would those changes also affect the `/explore` or only `/`?
I assume it would be good to get to an accessory page like mentioned here #18 when clicking on the image of the featured item. But would it be sufficient just to get to the official manufacturer page before #18 gets implemented?

**Comment by BalestraPatrick** [comment]
I think we can create a `HomeController` that will take care of the `/` route and render a new `home.leaf` template which will be very similar to the current `explore.leaf` template. After that, we can remove the `ExploreController`that is currently handling that same route: https://github.com/BalestraPatrick/HomeKitty/blob/13c87381e9ec210792a1cf8773e35897b29cf900/Sources/App/Controllers/ExploreController.swift#L14

Yes, clicking on the image would open the manufacturer page for now. As soon as #18 is implemented, we can then link to it 😃 
Feel free to assign yourself the issue when you're ready to start.

**Comment by fnoah** [comment]
It seems like I don't have permission to assign myself to the issue.

**Comment by BalestraPatrick** [comment]
Just invited you as collaborator. Feel free to create a branch directly in this repo if you prefer. 

For any questions, just let me know here or join the #development channel on [Slack](https://homekitty-slack.herokuapp.com).

**Comment by fnoah** [comment]
Thank you!
Once I have made some progress I'll push them to a new branch on this repo. When I am done implementing this feature, I'd be glad if you could review the code I wrote.

**Comment by BalestraPatrick** [comment]
@fnoah Sounds good!

**Comment by fnoah** [comment]
@BalestraPatrick I’m just working on this issue and most of the discussed features are implemented by now. As you said, the `HomeController` will be the new `/`, but should the `ExploreController` still be available at `/explore` and should the sidebar catgegory links on `/` still redirect to `/explore?category=` or should `/explore` be omitted completely?
In case `/explore` will be omitted completely, I think the `HomeController` would have to display the categories from the sidebar `/?category=`, maybe even with a separate view similar (or identical) to `explore.leaf`

**Comment by BalestraPatrick** [comment]
@fnoah I think we can keep the `explore` route. The `HomeController` would still display the sidebar and when a category is pressed, it should still open the correct `/explore?` route with the query. 

In this way, we only change the homepage where users will land as soon as they visit the website, and they can choose to explore accessories in the `/explore` directory by using the sidebar. Does that make sense to you? 😃

**Comment by fnoah** [comment]
I just opened a pull request with the changes I've made concerning this issue. For now, I have just selected some arbitrary ID in the `HomeController` for the featured accessory since I don't know the IDs from the accessories in the production database. The banner image is located in the `Public/images` folder and is also being selected from the `HomeController`.

I wrote a small Date extension that can generate a string like `added 1 day ago` but I haven't included it in the pull request because I have some troubles calling the function on an accessory object from a `.leaf`. As soon as I have time, I'll find a workaround for this.

**Comment by BalestraPatrick** [comment]
@fnoah Very cool, I am going to take a look at the PR right now. 
Regarding how to call a function from `.leaf`, you have to use JavaScript to make it interactive. You can take a look at how I do it here:
https://github.com/BalestraPatrick/HomeKitty/blob/0941dd54c4f0ced68c6f17e1c863cffda4bc180b/Resources/Views/contribute.leaf#L105

For example, you could have a function that does it when the page loads in JavaScript. 

On another thought, a better solution would be to do the calculation in Swift, and pass it as a parameter in the `Node` of an accessory so that the `.leaf` can render it as soon as it's displayed without waiting for the JavaScript to do it.
