### ISSUE TITLE
Show "Requires Bridge" badge to accessories

### ISSUE THREAD

**Issue by BalestraPatrick** [BalestraPatrick/HomeKitty#26]
An accessory that requires an hub to work with HomeKit would need a badge (much like the current coming soon yellow badge implemented in #25). We could also link to the specific hub required so that more information can be seen.

**Comment by BNTR** [comment]
Hello! I can try to help with that =) As I understand I need image for that and add some field to 'Accessory.swift'?

**Comment by BalestraPatrick** [comment]
Hello @BNTR, thanks for stepping up! 
I am going to describe how you could approach this feature:
1. Seed your database locally and add two columns to the `accessory` table. One column would be a boolean that tracks if the accessory needs a bridge. Another column would contain the id of the hub accessory. For example, the Philips Hue lights would have the `requiresHub` boolean set to `true` and the `requiredHub` identifier set to the Philips Hue Bridge `id`.
2. You would then modify and add these properties to the `Accessory.swift` (pretty much like I did in #17).
3. After than, it's just a matter of rendering the hub icon for now when the displayed accessory as the `requiresHub` property set to true like in #25.

Let me know if you have any questions, happy to guide you through this! 😄

**Comment by BNTR** [comment]
Sounds good! I'll start working with that and write here if I have any questions =)

**Comment by BalestraPatrick** [comment]
@BNTR Awesome, just invited you as collaborator so you can assign yourself the issue 👍

**Comment by BNTR** [comment]
@BalestraPatrick can you help me with icon for this issue? And should it behave like icon with pop-up (as #25)

**Comment by BalestraPatrick** [comment]
Here is the icon you can use. It's should be the same size as the `coming-soon.png` icon. 
Exactly, when hovering it it should show the popover which says "This accessory requires a proprietary bridge.". When clicking on the icon, if possible (we can always do it later), we should open the bridge link.

![requires-bridge](https://user-images.githubusercontent.com/3658887/31253100-c8599668-aa23-11e7-95bf-1ef5299d95e9.png)

**Comment by BNTR** [comment]
I think tap on icon better do after #18 , when we would be able to show single device page.
