### ISSUE TITLE
Add "All accessories" category

### ISSUE THREAD

**Issue by BalestraPatrick** [BalestraPatrick/HomeKitty#30]
Users should be able to see all accessories in a single page. Maybe we should a special category or button in the sidebar.

**Comment by nhultz** [comment]
hey @BalestraPatrick  I can try to help with this one.  Anything particular you are thinking as far as looks or just the same as the other accessory pages with more items?

**Comment by nhultz** [comment]
Cool. That sounds straight forward enough.  Looks like adding the Manufacturers is going to be basically the same so I'll see if I can knock out #31 as well :smile:

**Comment by BalestraPatrick** [comment]
@nhultz I just added you as collaborator, feel free to assign this issue and the other one if you'd like to yourself 👍

**Comment by nhultz** [comment]
@BalestraPatrick  quick question about the icons.  Is there a standard collection you are looking through for the icons that are in the project so far or are they all custom?

**Comment by BalestraPatrick** [comment]
Closed by #43
