### ISSUE TITLE
Fix vertical alignment of hamburger button on mobile

### ISSUE THREAD

**Issue by BalestraPatrick** [BalestraPatrick/HomeKitty#34]
The hamburger menu button should be vertically centered. If you like CSS, this is for you 😄 
![img_4733](https://user-images.githubusercontent.com/3658887/31199872-12b7118e-a959-11e7-876f-17155505f7c2.jpg)

**Comment by jimjja** [comment]
I can have a look at this

**Comment by BalestraPatrick** [comment]
Great, thanks a lot @jimjja! The issue should be somewhere in the bootstrap, I think we could override some property to customize its position.

**Comment by BalestraPatrick** [comment]
Closed by #36
