### ISSUE TITLE
Add region information for each accessory

### ISSUE THREAD

**Issue by BalestraPatrick** [BalestraPatrick/HomeKitty#5]
We should have information about where each accessory is available.

**Comment by BNTR** [comment]
@BalestraPatrick can you provide any info about this task? How it should work and look from your perspective?

**Comment by BalestraPatrick** [comment]
Hey @BNTR! I think this depends on #18 since we don't want to have too many information inside each accessory box. After that's done, we could create a table called `Regions` that has all the available regions. 
Since most of the restrictions regarding accessories are only related to socket plugs, we can store each main region. For example, UK, EU, CH, US and so on. In short, this table would contain all possible regions.
We can then create a new column on the `Accessory` table that stores the IDs of each supported region. In this case, we would need a many-to-many relationship which is described very well in this article: https://geeks.brokenhands.io/blog/posts/fluent-part-3-sibling-relationships/

**Comment by BNTR** [comment]
@BalestraPatrick can I try do this task without #18 is done?
