### ISSUE TITLE
Validate price input to avoid submitting text

### ISSUE THREAD

**Issue by BalestraPatrick** [BalestraPatrick/HomeKitty#53]
We should to some input validation in the price input in the `contribute.leaf` page. We should only accept numbers.

**Comment by nhultz** [comment]
I can pick this one up.  @BalestraPatrick do you still want users to be able to enter the `$` in the price?

**Comment by BalestraPatrick** [comment]
@nhultz We don't need the `$` since we add it in the backend already before saving the price to the database. I'd say the format of the price must be something like `5.95` or `15.99`. Since we're only tracking US prices right now, we can also automatically add the two digits after the dot if the user doesn't write them and the input goes out of focus. What do you think?

**Comment by nhultz** [comment]
Yeah I'm thinking of changing the input to be a number input should handle most of it and then maybe a little snippet of Javascript to add the extra 00's.

**Comment by BalestraPatrick** [comment]
Closed by #56
