### ISSUE TITLE
Add RSS feed to subscribe to homepage of latest accessories

### ISSUE THREAD

**Issue by BalestraPatrick** [BalestraPatrick/HomeKitty#59]

**Comment by moritzsternemann** [comment]
Gonna be working on this... 💪

**Comment by BalestraPatrick** [comment]
Thank you @moritzsternemann! I just invited you to the repo so that you can assign the issue to you. 
If you need some inspiration, I previously noticed that this project already has an RSS/Atom feed generator, so that would be a nice starting point: 
- https://github.com/brokenhandsio/SteamPress/blob/0a346a23846d51c8674452dee38b879885318742/Sources/SteamPress/Feed%20Generators/RSSFeedGenerator.swift
- https://github.com/brokenhandsio/SteamPress/blob/9c5b18ef3daff5e14c9783d780afd566298ff496/Sources/SteamPress/Feed%20Generators/AtomFeedGenerator.swift

**Comment by moritzsternemann** [comment]
Should we implement RSS, Atom or both here?

**Comment by BalestraPatrick** [comment]
@moritzsternemann Not an expert in this but I think RSS is more common and was requested more compared to Atom.
