### ISSUE TITLE
Migrate to Swift 4

### ISSUE THREAD

**Issue by BalestraPatrick** [BalestraPatrick/HomeKitty#8]
The project is now written in Swift 3 and works great with Xcode 9. We should migrate to Swift 4 as soon as possible to keep up to date with Vapor latest features too.

**Comment by wolffan** [comment]
can't do 'swift build' :/

**Comment by BalestraPatrick** [comment]
@wolffan Hey! To migrate to Swift 4 you may want to follow this post which goes through all the changes (starting from `Package.swift` which is why you can not run `swift build`): https://geeks.brokenhands.io/blog/posts/migrating-your-server-side-app-to-swift-4/

**Comment by wolffan** [comment]
Thanks @BalestraPatrick I'll do that. But also the migrator didn't run so was a bit lost :)
