### ISSUE TITLE
Add "Programmable Switch" category

### ISSUE THREAD

**Issue by renssies** [BalestraPatrick/HomeKitty#87]
Currently the the Switches category is filled with actual HomeKit switches but also "Stateless Programmable Switches" such as Hue Tap, Hue Dimmer and Logitech pop. 

So I think there should be a new "Programmable Switch" for these kinds of "Trigger" switches.

**Comment by BalestraPatrick** [comment]
This is a good idea but I think it's better if we follow Apple's official categories to make things easier to find.
